### PR TITLE
MergeMarauderHuman

### PR DESCRIPTION
**Pull request by LocalGod79**
removed marauder planet

merge Class C Freighter first to avoid conflicts.

### CODE REVIEW

**Comment by Wrzlprnft** [comment]
I made a significant mistake while firstly implementing the marauder ships, maybe we can pack the all into the main human shipyard?

**Comment by LocalGod79** [comment]
i think that the way you had implemented it was quite elegant, and i wouldn't have thought anything of it if it hadn't been a bug report on Steam, recently - four ports in a system causes ui overlap in the ports map screen.

**Comment by Wrzlprnft** [comment]
It is elegant, but one can not compare all the stats. I'm fine with this change, and i do like the existing system, too.

**Comment by LocalGod79** [comment]
unless you buy them, and visit a shipyard...

**Pull request merged**
