### PR TITLE
Added a system for mods (WIP)

### PR DESCRIPTION
**Pull request by Amazinite**
This is what I have so far. I didn't want to go any farther then get a no on the idea. So this way there are a ton of random planets all throughout the system. It's kind of cluttered, but also makes it feel like you're in a shopping mall with a ton of cool stores around you. From here it would just be a matter of going to each mod and collecting all the outfits and ships from them.

### CODE REVIEW

**Comment by LocalGod79** [comment]
a mods planet exists with the deprecated outfits planet

**Comment by Wrzlprnft** [comment]
I was talkung with derpy and trusted him with coming up with something.

**Comment by Amazinite** [comment]
I know about that planet, but it's intent seems to be if someone wants to modify the plugin to test their own items. This "Steam Mods" system splits up each mod into their own planet and will allow people to get anything they want that is from a mod if that mod planet exists and they have the mod installed.

**Comment by LocalGod79** [comment]
you face the issue of the "4 port limit" for the ui map screen - more than three, and u.i. things start to overlap...

edit, and it sounds like the mod would have to contain the planet within a worldforge system, so why not just apply the outfitters to the worldforge planet already provided?

i'm not being snarky - i'm confused.

**Comment by Amazinite** [comment]
I don't really see the 4 port limit thing as an issue. What would be the need to look at it, as there's no useful information that it would really give. 

And the other mods wouldn't need to contain anything for World Forge within them, it's World Fprge that will contain custom outfitters within itself. These outfitters and shipyards would be filled with the names of stuff from those mods, so if say Shields Up is installed, then the Shields Up planet will have the shipyard and outfitter present that offer things from the mod.

**Comment by Amazinite** [comment]
This is just a WIP pull; I'll do the shipyards and outfitters for all the mods later.

**Comment by LocalGod79** [comment]
i understand better now.

i think that @Wrzlprnft planet description is a cleaner solution (stuff that causes ui conflicts irks the o.c.d. in me) - multiple mods at the same planet, with the ownership of each outfit listed under plugin headers within the planet description.

**Comment by Amazinite** [comment]
messed up ui

7 spaceports then it goes off my screen xD
my game window is 1919x~1018.

**Comment by Amazinite** [comment]
I want to rework this later to not have it be so cluttered, as well as turn it into multiple systems for different mods.

**Pull request closed without merging**
